
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta name="viewport" content="width=device-width">

<style type="text/css">
img {
max-width: 100%;
}
body {-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6;}
body {background-color: #e9e9e9;}

@media only screen and (max-width: 640px) {
   h1 {
	 font-weight: 600 !important; margin: 20px 0 5px !important;
   }
   h2 {
     font-weight: 600 !important; margin: 20px 0 5px !important;
   }
   h3 {
     font-weight: 600 !important; margin: 20px 0 5px !important;
   }
   h4 {
     font-weight: 600 !important; margin: 20px 0 5px !important;
   }
   h1 {
     font-size: 22px !important;
   }
   h2 {
     font-size: 18px !important;
   }
   h3 {
     font-size: 16px !important;
   }
   .container {
     width: 100% !important;
   }
   .content {
     padding: 10px !important;
   }
   .content-wrap {
     padding: 10px !important;
   }
   .invoice {
     width: 100% !important;
   }
}
</style>
</head>

<body itemscopeitemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6; background: #e9e9e9; margin: 0;">

<table class="body-wrap" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background: #e9e9e9; margin: 0;">
	<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
		<td style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top">
		</td>
		<td class="container" width="800" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 800px !important; clear: both !important; margin: 0 auto;" valign="top">
			<div class="content" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
				<table class="main" width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background: #fff; margin: 0; border: 1px solid #e9e9e9;">
					<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
						<td class="alert alert-warning" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 24px; vertical-align: top; color: #fff; font-weight: 500; text-align: center; border-radius: 3px 3px 0 0; background: #CC0000; margin: 0; padding: 15px; border: 7px solid #ffffff;" align="center" valign="top">
							IT Service Bulletin
						</td>
					</tr>
					<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
						<td class="content-wrap" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 7px;" valign="top">
							<table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0; border-collapse: collapse;">
								
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Subject: 
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										{{subject}}
									</td>
								</tr>
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Impacted Service(s):
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										{{impacted_services}}
									</td>
								</tr>
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Affected Region(s):
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										{{affected_regions}}
									</td>
								</tr>
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Outage Start:
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										{{outage_start_time | date('F jS \, Y h:i:s A')}}
									</td>
								</tr>
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Description:
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										{{description}}
									</td>
								</tr>
								<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
									<td width="30%" class="aligncenter content-block" style="background-color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9; font-size: 14px; vertical-align: top; margin: 0; padding: 5px; font-weight: bold; color: #008EAA;" valign="top" align="left">
										Status Update:
									</td>
									<td width="70%" class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; border-top: 1px solid #e9e9e9	; font-size: 14px; vertical-align: center; margin: 0; padding: 5px;" valign="center" align="left">
										 {{status_update}}
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				<div class="footer" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #000000; margin: 0;">
					<table width="100%" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0; color: #000000;">
						<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
							<td class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; text-align: center; margin: 0; padding: 5px;" align="center" valign="top">
								For Questions or concerns, please contact the HDS IT Help Desk and reference Service Manager Incident {{ticket_number}}.
							</td>
						</tr>
						<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
							<td class="aligncenter content-block" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; text-align: center; margin: 0; border-top: 1px solid #000000; padding: 5px;" align="center" valign="top">	
									US & Canada: 866-HDS-WINS (866-437-9467)</br>
									Australia: 1-800-800-261</br>
									EMEA: +44 1753 618500</br>
									International: 1-408-327-4000
							</td>
						</tr>
					</table>
				</div>
			</div>
		</td>
		<td style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top">
		</td>
	</tr>
</table>

</body>
</html>
